#!/bin/bash
# Runs the EC Learner on openmind.

module add openmind/singularity

TIMEOUT=$1

echo "Launching time ($TIMEOUT seconds)"

# Make a M-D-Y stamped dir if we don't already have one.
DATE=$(date +%m-%d-%Y)
mkdir -p jobs/$DATE
OUTPUT=jobs/$DATE/ec_learner_debug_$TIMEOUT
echo "Logging to: $OUTPUT"

srun --job-name=$OUTPUT --output=$OUTPUT --ntasks=1 --mem-per-cpu=50000 --cpus-per-task 1 --time=10:00 --qos=tenenbaum \
  singularity exec -B /om2  ../dev-container.img python ecLearner.py \
  -t $TIMEOUT -i 3 --compressor ocaml --solver python \
  --pseudoCounts 5.0 --aic 0.01 --structurePenalty 0.01 --topK 2 --arity 5 \
  --storeTaskMetrics  \
  --CPUs 10 \
  --taskBatchSize 30 \
  --no-recognition \
  --Helmholtz 0 \
  &
