version: 2.1
jobs:
  build:
    docker:
      - image: jrgauthier/puddle-world-dev:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: nosetests
